name: Deploy Production

on:
  push:
    branches: [main]

jobs:
  deploy_full:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker-compose.yml
          push: true
          tags: |
            ${{ secrets.DOCKER_USER }}/client:latest
            ${{ secrets.DOCKER_USER }}/api:latest
            ${{ secrets.DOCKER_USER }}/bot:latest
          cache-from: |
            type=registry,ref=${{ secrets.DOCKER_USER }}/client-deps:latest
            type=registry,ref=${{ secrets.DOCKER_USER }}/api-deps:latest
            type=registry,ref=${{ secrets.DOCKER_USER }}/bot-deps:latest
          cache-to: type=inline,mode=max

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            export DOCKER_USER=${{ secrets.DOCKER_USER }}
            cd ~/www/cyberslavs.fun
            
            # Принудительное удаление всех ресурсов
            docker compose down -v --rmi local --remove-orphans
            
            # Загрузка новых образов
            docker compose pull
            
            # Пересборка и запуск
            docker compose up -d --build --force-recreate
            
            # Очистка
            docker system prune -f