name: Deploy Production

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Client
        uses: docker/build-push-action@v5
        with:
          context: client
          file: client/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USER }}/client:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USER }}/client-deps:latest
          cache-to: type=inline,mode=max

      - name: Build and Push API
        uses: docker/build-push-action@v5
        with:
          context: api
          file: api/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USER }}/api:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USER }}/api-deps:latest
          cache-to: type=inline,mode=max

      - name: Build and Push Bot
        uses: docker/build-push-action@v5
        with:
          context: bot
          file: bot/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USER }}/bot:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USER }}/bot-deps:latest
          cache-to: type=inline,mode=max

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ~/www/3dating.fun
            docker compose down
            docker compose pull
            docker compose up -d --build
            docker system prune -f