name: Manual Full Deploy DatingApp

on:
  workflow_dispatch

jobs:
  deploy_manual:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Check Docker and Docker Compose Versions
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ~/www/cyberslavs.fun/

            docker --version
            docker compose version || docker-compose version

            docker system prune --force --all --volumes
            docker compose down --rmi=local

            git pull
            git submodule update --init --recursive --remote
            docker compose up -d --build 
