name: Deploy Production

on:
  push:
    branches: [main]
    paths-ignore:
      - 'client/**'
      - 'api/**'
      - 'bot/**'

jobs:
  deploy_full:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USER }}/app:latest
          cache-from: |
            type=registry,ref=${{ secrets.DOCKER_USER }}/app:buildcache
            type=registry,ref=${{ secrets.DOCKER_USER }}/client-deps:latest
            type=registry,ref=${{ secrets.DOCKER_USER }}/api-deps:latest
            type=registry,ref=${{ secrets.DOCKER_USER }}/bot-deps:latest
          cache-to: type=inline,mode=max

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ~/www/cyberslavs.fun
            docker compose down
            docker compose pull
            docker compose up -d --build
            docker image prune -af
            echo "=== Current Containers ==="
            docker compose ps -a