name: Deploy Submodules

on:
  repository_dispatch:
    types: [submodule_update]

jobs:
  detect_changes:
    runs-on: ubuntu-latest
    outputs:
      changed_submodules: ${{ steps.check-modules.outputs.changed_submodules }}
      root_changed: ${{ steps.check-modules.outputs.root_changed }}

    steps:
      - name: Checkout with full history
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 2

      - name: Get changes
        id: check-modules
        run: |
          # Изменения в подмодулях
          CHANGED_SUBMODULES=$(git diff --name-only HEAD^ HEAD | grep -o 'submodules/.*/' | cut -d'/' -f2 | sort -u | jq -R -s -c 'split("\n")[:-1]')
          
          # Изменения в корне
          ROOT_CHANGED=$(git diff --name-only HEAD^ HEAD | grep -vE '^(client|api|bot|submodules)/' | wc -l)
          
          echo "changed_submodules=$CHANGED_SUBMODULES" >> $GITHUB_OUTPUT
          echo "root_changed=$ROOT_CHANGED" >> $GITHUB_OUTPUT

  deploy_services:
    needs: detect_changes
    if: ${{ needs.detect_changes.outputs.changed_submodules != '[]' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ${{ fromJson(needs.detect_changes.outputs.changed_submodules) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.service }}
          file: ${{ matrix.service }}/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USER }}/${{ matrix.service }}:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USER }}/${{ matrix.service }}-deps:latest
          cache-to: type=inline,mode=max

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ~/www/cyberslavs.fun
            docker compose pull ${{ matrix.service }}
            docker compose up -d --force-recreate ${{ matrix.service }}
            docker system prune -f

  deploy_root:
    needs: detect_changes
    if: ${{ needs.detect_changes.outputs.root_changed > 0 }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

          
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ~/www/cyberslavs.fun
            docker compose pull
            docker compose up -d --force-recreate
            docker system prune -f