name: Deploy DatingApp to Production

on:
  push:
    branches:
      - main

jobs:
  deploy_full:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Execute Deployment on VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ~/www/cyberslavs.fun/
            
            # Force cleanup
            git reset --hard HEAD
            git clean -fd
            
            # Update repo and submodules
            git checkout main
            git pull origin main
            git submodule update --init --recursive --remote --force
            
            # Docker operations
            docker compose down --rmi local --volumes --remove-orphans
            docker compose up -d --build --force-recreate
            
            # Cleanup old images
            docker image prune -af
            
            # Verification
            echo "=== Current Docker Containers ==="
            docker compose ps
            echo "=== Latest Docker Images ==="
            docker images --filter "reference=datingapp*" --format "table {{.ID}}\t{{.Repository}}\t{{.Tag}}"