name: Deploy DatingApp to Production

on:
  push:
    branches:
      - main

jobs:
  deploy_full:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: SSH Deployment Commands
        uses: appleboy/ssh-action@v1.0.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ~/www/cyberslavs.fun/
            docker compose down --rmi local --remove-orphans
            git reset --hard HEAD

            git clean -fd
            git checkout main
            git pull origin main --ff-only

            git submodule sync
            git submodule update --init --recursive --remote --force

            docker compose up -d --build --force-recreate --remove-orphans
            

            docker image prune -af
            docker volume prune -f
            

            echo "Current containers:"
            docker compose ps -a