name: Deploy Submodules

on:
  repository_dispatch:
    types: [submodule_update]

jobs:
  deploy_service:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ${{ fromJson(github.event.client_payload.services || '[]') }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          ref: ${{ github.event.client_payload.ref || 'main' }}

      - name: Validate service
        run: |
          if [ ! -d "${{ matrix.service }}" ]; then
            echo "Service directory ${{ matrix.service }} not found!"
            exit 1
          fi

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.service }}
          file: ${{ matrix.service }}/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USER }}/${{ matrix.service }}:latest
            ${{ secrets.DOCKER_USER }}/${{ matrix.service }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_USER }}/${{ matrix.service }}-deps:latest
          cache-to: type=inline,mode=max

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            export DOCKER_USER=${{ secrets.DOCKER_USER }}
            cd ~/www/cyberslavs.fun
            docker compose pull ${{ matrix.service }}
            docker compose up -d --force-recreate ${{ matrix.service }}
            docker system prune -f