name: Deploy Production

on:
  push:
    branches: [main]

jobs:
  detect_changes:
    runs-on: ubuntu-latest
    outputs:
      changed_services: ${{ steps.check-changes.outputs.changed_services }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get changed services
        id: check-changes
        run: |
          CHANGED_SERVICES=$(git diff --name-only HEAD^ HEAD | grep -oE '^(client|api|bot)/' | sort -u | sed 's/\///' | jq -R -s -c 'split("\n")[:-1]')
          echo "changed_services=$CHANGED_SERVICES" >> $GITHUB_OUTPUT

  deploy_full:
    needs: detect_changes
    if: ${{ needs.detect_changes.outputs.changed_services != '[]' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ${{ fromJson(needs.detect_changes.outputs.changed_services) }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.service }}
          file: ${{ matrix.service }}/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USER }}/${{ matrix.service }}:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USER }}/${{ matrix.service }}-deps:latest
          cache-to: type=inline,mode=max

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ~/www/cyberslavs.fun
            docker compose pull ${{ matrix.service }}
            docker compose up -d --build --force-recreate ${{ matrix.service }}
            docker image prune -f